dataset: "./data/era5_1p5.yml"

model:
  type: vit            # vit or persistence
  dim: 256
  num_layers: 12
  num_heads: 4
  dim_heads: 64
  patch_size: [8, 11]   # (ww, hh)
  ffn_factor: 2
  separable_embed: True
  noise: "adaLN"
  spatial_mixer: "sfno"
  noise_dim: 16
  dropout: 0.00
  time_embed: 8
  latlon_embed: True
  latlon_pe: "wrap"
  surface_geopotential: True
  land_sea_mask: True
  global_skip: True

loss:
  name: crps
  kwargs:
    reduction: sphere  # "sphere" (corrects for distorted grid), "mean" naive mean
    nlat: 121
    nlon: 240

trainer:
  lr: 2.0e-3
  batch_size: 32
  ensemble_size: 2
  weight_decay: 0.01
  betas: [0.9, 0.95]
  max_steps: 20000
  num_data_workers: 0
