dataset: "./data/era5_2p8_3l.yml"

model:
  type: wet            # vit or persistence
  dim: 256
  num_layers: 8
  num_heads: 4
  dim_heads: 64
  patch_size: [4, 4]   # (patch_lat, patch_lon)
  ffn_factor: 2
  separable_embed: True
  spatial_mixer: "afno"
  noise_dim: 16
  dropout: 0.00
  time_embed: 8
  latlon_embed: True
  latlon_pe: "wrap"
  surface_geopotential: True
  land_sea_mask: True
  aux_spatial_dim: 32
  graph_conv: True
  graph_conv_level: 1
  graph_conv_layers: 1
  graph_conv_node_embed: 8
  graph_conv_edge_embed: 8
  global_skip: False

loss:
  name: crps
  kwargs:
    reduction: sphere  # "sphere" (corrects for distorted grid), "mean" naive mean
    nlat: 64
    nlon: 128

trainer:
  lr: 1.0e-3
  batch_size: 24
  ensemble_size: 2
  weight_decay: 0.01
  betas: [0.9, 0.95]
  max_steps: 20000
  num_data_workers: 0
